apiVersion: v1
kind: Namespace
metadata:
  name: c2c-new-ecr-ns
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: c2c-new-ecr-deployment
  namespace: c2c-new-ecr-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: back-end
          image: 792373136340.dkr.ecr.us-east-2.amazonaws.com/c2c:c0fb17ed32026e3eb6f0f8e75447dba6bc511cb9

---
#Service
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: c2c-new-ecr-label
  name: c2c-new-ecr-service
  namespace: c2c-new-ecr-ns
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web
  sessionAffinity: None
  type: LoadBalancer

---